namespace: mellanox
name: onyx
version: 1.0.0
readme: README.md
authors:
- Samer Deeb (@samerd)
description: Collection for managing Mellanox onyx devices
license_file: LICENSE
tags:
  - mellanox
  - onyx
  - cliconf
  - network
dependencies:
  "ansible.netcommon": "*"
repository: https://github.com/ansible-collections/mellanox.onyx
documentation: https://github.com/ansible-collections/mellanox.onyx
homepage: https://github.com/ansible-collections/mellanox.onyx
issues: https://github.com/ansible-collections/mellanox.onyx/issues
