namespace: mellanox
name: onyx
version: 0.1.0
readme: README.md
authors:
- Samer Deeb (@samerd)
description: Collection for managing Mellanox onyx devices
license_file: LICENSE
tags:
  - mellanox
  - onyx
  - cliconf
  - network
dependencies: {}
repository: https://github.com/ansible-collections/mellanox.onyx.git
documentation: https://github.com/ansible-collections/mellanox.onyx.git
homepage: https://github.com/ansible-collections/mellanox.onyx
issues: https://github.com/ansible-collections/mellanox.onyx/issues
